stages:
    - build
    - test
    - deploy

build-my-first-job:
    grade: build
    script: echo "this is first build job"

test-my-first-job:
    grade: test
    script: echo "this is first test job"

deploy-my-first-job:
    grade: deploy
    script: echo "this is first deploy job"
