stages:
    - build
    - test
    - deploy

variables:
    # Define the base directory for Java classes to simplify commands
    CLASSES_DIR: out

build-my-first-job:
    stage: build
    image: ubuntu:22.04
    script:
        - echo "Updating packages and installing Java 22"
        - apt-get update -y
        - apt-get install -y wget
        - wget https://download.java.net/java/GA/jdk22/13/GPL/openjdk-22_linux-x64_bin.tar.gz
        - tar xvf openjdk-22_linux-x64_bin.tar.gz
        - export JAVA_HOME=$PWD/jdk-22
        - export PATH=$JAVA_HOME/bin:$PATH
        - java -version
        - echo "Building the project"
        - find src -name "*.java" > sources.txt
        - javac -cp src -d $CLASSES_DIR @sources.txt
    before_script:
        - export CLASSES_DIR=out



test-my-first-job:
    stage: test
    script:
        - echo "Running tests"
        # Assuming tests are in the 'model.tile' package and we compile them into the same 'out' directory
        - find test -name "*Test.java" > test_sources.txt
        - javac -cp src:test:$CLASSES_DIR -d $CLASSES_DIR @test_sources.txt
        # Run tests using the compiled classes and test classes
        # Note: Replace 'model.tile' with the correct package path if needed
        - java -cp $CLASSES_DIR org.junit.runner.JUnitCore model.tile.BlastTest model.tile.BlockTest model.tile.BombTest ... # etc.

deploy-my-first-job:
    stage: deploy
    script:
        - echo "Deploying the application"
        # Add your deployment commands here
